version: '2'
services:
    web:
        build:
            context: ./Dockerfiles/nginx
            dockerfile: ./Dockerfile
        ports:
            - "80:80"
        volumes:
            - ./app:/app
        links:
            - phpfpm
    phpfpm:
        build:
            context: ./Dockerfiles/phpfpm/7.0 # Avaible version are 7.0 and 5.7
            dockerfile: ./Dockerfile
        volumes:
            - ./app:/app
        links:
            - db:mysql
    db:
        image: mariadb:latest
        ports:
          - "3306:3306"
        volumes:
           - mysql:/var/lib/mysql
        environment:
           - MYSQL_ROOT_PASSWORD=root
           - MYSQL_DATABASE=test

volumes:
    mysql:
    code-sync:
        external: true